[package]
name = "mr-kaffee-2023-15"
description = "Solution to AoC 2023/15, http://adventofcode.com/2023/day/15/"
authors = ["Peter Wieland <peter@die-wielands.net>"]
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
